MaxCrawlCount: 20

DBUser: "newitop"
DBName: "itop"
DBPassWord: "rjjsoft+0591"

FilterMode: "strict"

ExtraHeaders:
 
ExtraHeadersString:

AllDomainReturn: false

SubDomainReturn: true

IncognitoContext: false

NoHeadless: true

PathByFuzz: false

Proxy: ""




