MaxCrawlCount: 20

DBUser: "iot"
DBName: "iot"
DBPassWord: "iot95976"

FilterMode: "simple"

ExtraHeaders:
 
ExtraHeadersString:

AllDomainReturn: false

SubDomainReturn: true

IncognitoContext: false

NoHeadless: true

PathByFuzz: false

Proxy: ""




